### ISSUE TITLE
从 cloud 路径生成外网 url

### ISSUE THREAD

**Issue by oovm** [bujnlc8/qcos#3]
`client.get_full_url_from_path` 得到的路径没法直接从外网访问, 有额外的校验

希望有个直接生成外网可访问链接的 api

https://github.com/hustclf/cos-rust-sdk/blob/main/src/auth.rs

**Comment by bujnlc8** [comment]
已经加上了，见[例子](https://github.com/bujnlc8/qcos/blob/80a28fa8c093c1ff9340c5900f880c5a599339b4/examples/objects.rs#L87)

**Comment by oovm** [comment]
好的
