### ISSUE TITLE
分片上传的问题

### ISSUE THREAD

**Issue by rosejober** [bujnlc8/qcos#5]
1、文件上传接口内部看到都是调用put_object_get_upload_id获取新的upload_id，这样如果上次上传失败了，就不能继续接着上传，这种情况对上传大文件来说是个灾难，特别对于手机网络来说，会很容易文件上传不成功。
2、对于已经存在的文件，也没有看到针对文件md5值校验是否存在的功能，如果存在理论上直接返回成功就好了，这样速度又快，又节省流量。
3、上传接口中需要指定key，这个参数看代码其实是指定的url后面的文件名；如果能做到外部指定了就用外部的，外部没指定自己算文件md5再加文件后缀，会不会更好？
4、rust返回成功还是失败一般都是Result<成功，失败原因>，结果现在看现有接口成功失败返回都在一个对象中，这样?运算都用不了，设计不太好。
5、内部所谓的开线程，其实用的是tokio::spawn，这个函数创建的不是线程，是往线程池中添加任务，线程数目由开始创建的运行时时候指定的。

**Comment by bujnlc8** [comment]
感谢你的建议与意见，有些是由于历史原因不便做break changes，有些确实是设计的问题，欢迎提mr或fork后自行修改
